/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jintArray JNICALL Java_game_algorithm_CppInterface_makeFirst
  (JNIEnv *, jobject, jintArray);

JNIEXPORT jintArray JNICALL Java_game_algorithm_CppInterface_makeRandom
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
